config/routes.rb
Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  devise_for :users
  
  root 'learn#index'

  get 'feedback', to: 'feedback#index', as: :feedback
  get 'learn', to: 'learn#index', as: :learn
  get 'practice', to: 'skills#practice', as: :practice

  get '/test_group_page/:group' => 'test_group_pages#show', as: :test_group_page
  get '/test_group_pages' => 'test_group_pages#index', as: :test_group_pages

  resources :exercises, only: [:index, :show] do
    member do
      post 'evaluate'
    end
  end

  resources :units, only: [:index, :show]
  resources :resources, only: [:show]
  resources :learner, only: [:update]
  resources :learner_logs, only: [:destroy]
  resources :user_activity_states, only: [:create]
  resources :user_activity_logs, only: [:create]


  # applications
  resources :participant_applications do
    member do
      get 'confirmation', as: :confirmation
    end
  end

  get 'application', to: 'participant_applications#new'

  # user
  resources :users

end

app/views/shared/_exercise.html.erb
 <div class="exercise"> 
  <div class="<%= params[:exercise] == exercise.id.to_s ? "panel panel-success" : "panel panel-default" %>" id="exercise-<%= exercise.id %>">
    <div class="panel-heading">
      <h4>Übung</h4>
    </div>
    <div class="panel-body">
      <% if defined?(show_as_modal) && show_as_modal %>
        <div class="row">
          <div class="col-lg-1 col-sm-offset-1">
            <%= simple_form_for :exercise, url: exercise_path(exercise), method: :get, remote: true do |f| %>
              <%= f.button :submit, "» Übung starten", class: "btn btn-success btn-lg" %>
            <% end %>
          </div>
        </div>
      <% else %>
        <%= render 'exercises/exercise', exercise: exercise %> 
      <% end %>
    </div>
    <div class="panel-footer">
      <% if ENV['DEBUG'] %>
          <small><%= link_to "id: #{exercise.wp_id} - #{exercise.type}", exercise_path(exercise) %></small>
          <small><%= exercise.wp_id %></small>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_exercise_as_plain_form.html.erb
<% if exercise.type == Exercise::TYPE_CLOZE %>
  <%= f.simple_fields_for :exercise do |f| %>
    <%= f.simple_fields_for :solutions do |f| %>
      <div class="exercise">
        <% content = exercise.parsed_content %>
            <% unless content[:description].nil? %>
            <div class="block-markup prompt">
              <div class="paragraph">
                <%= raw content[:description]%>
              </div>
            </div>
            <% end %>
        <% content[:text].split('%s').each_with_index do |t, i| %>
          <%= raw t %>
          <span id="blank_wrapper_<%= i %>_<%= exercise.id %>">
            <% if content[:blanks][i] && content[:blanks][i][:suggestions] && content[:blanks][i][:suggestions].count > 1 %>
              <%= f.input_field "#{i}", collection: content[:blanks][i][:suggestions], class: "", style: "background-color: white" if content[:blanks][i] %>
            <% elsif content[:blanks][i] %>
              <%= f.input_field "#{i}", class: "" if content[:blanks][i] %>
            <% end %>
          </span>
        <% end %>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_feedback_items.html.erb
        <li><%= link_to "Visuelles Feedback", { controller: "feedback", action: "index", feedback: :skill_tree } %></li>
        <li><%= link_to "Momentaufnahme", { controller: "feedback", action: "index", feedback: :moment } %></li>
        <li><%= link_to "Text-Feedback", { controller: "feedback", action: "index", feedback: :text } %></li>
        <li><%= link_to "Hybrides Feedback", { controller: "feedback", action: "index", feedback: :hybrid } %></li>
        <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Empfehlungen
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                        <li><%= link_to "Empfehlungen 1", { controller: "feedback", action: "index", feedback: :recommendations, style: :recommendations } %></li>
                        <li><%= link_to "Empfehlungen 2", { controller: "feedback", action: "index", feedback: :recommendations, style: :recommendations_average } %></li>
                        <li><%= link_to "Empfehlungen 3", { controller: "feedback", action: "index", feedback: :recommendations, style: :recommendations_untouched } %></li>
                </ul>
        </li>
        <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Fortschritt
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                <li><%= link_to "Die letzten 10 Minuten", { controller: "feedback", action: "index", feedback: :progress, scale: 10.minutes } %></li>
                <li><%= link_to "Die letzten 30 Minuten", { controller: "feedback", action: "index", feedback: :progress, scale: 30.minutes } %></li>
                <li><%= link_to "Die letzte Stunde", { controller: "feedback", action: "index", feedback: :progress, scale: 1.hour } %></li>
                <li><%= link_to "Die letzten 2 Stunden", { controller: "feedback", action: "index", feedback: :progress, scale: 2.hour } %></li>
                <li><%= link_to "Die letzten 12 Stunden", { controller: "feedback", action: "index", feedback: :progress, scale: 2.hour } %></li>
                <li><%= link_to "Der letze Tag", { controller: "feedback", action: "index", feedback: :progress, scale: 12.hour } %></li>
                <li><%= link_to "Die letzte Woche", { controller: "feedback", action: "index", feedback: :progress, scale: 1.week } %></li>
                <li><%= link_to "Der letzte Monat", { controller: "feedback", action: "index", feedback: :progress, scale: 1.month } %></li>
                <li><%= link_to "Seit beginn", { controller: "feedback", action: "index", feedback: :progress, scale: -1 } %></li>
                </ul>
        </li>
        <li><%= link_to "Logbuch", { controller: "feedback", action: "index", feedback: :learner_log } %></li>

app/views/shared/_feedback_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Feedback:</a>
    </div>

      <ul class="nav navbar-nav">
        <%= render 'shared/feedback_items' %>
      </ul>
    </div>
</nav>

app/views/shared/_modal.js.erb
function doModal(heading, center, formContent) {
    html =  '<div id="dynamicModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="confirm-modal" aria-hidden="true">';
    html += '<div class="modal-dialog">';
    html += '<div class="modal-content">';
    html += '<div class="modal-header">';
    html += '<a class="close" data-dismiss="modal">×</a>';
    html += '<h4>'+header+'</h4>'
    html += '</div>';
    html += '<div class="modal-body">';
    html += '<center><b>'
    html += center
    html += '</b></center></br>'
    html += content;
    html += '</div>';
    html += '<div class="modal-footer">';
    html += '<span class="btn btn-primary" data-dismiss="modal">Close</span>';
    html += '</div>';  // content
    html += '</div>';  // dialog
    html += '</div>';  // footer
    html += '</div>';  // modalWindow
    $('body').append(html);
    $("#dynamicModal").modal();
    $("#dynamicModal").modal('show');

    $('#dynamicModal').on('hidden.bs.modal', function (e) {
        $(this).remove();
    });
}

function hideModal()
{
    // Using a very general selector - this is because $('#modalDiv').hide
    // will remove the modal window but not the mask
    $('.modal.in').modal('hide');
}

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-inverse main-navbar navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to root_path, class: "navbar-brand", style: " margin-top: -7px;" do %>
        <%= image_tag '/favicon.ico', style: "display: inline; max-height:36px; margin-right: 5px;" %>
        KnowYourLanguage
      <% end %>
    </div>
    <% if user_signed_in? %>
    <ul class="nav navbar-nav">
      <% if request.path_info == '/units' %>
        <li class="active"><%= link_to 'Lernen', learn_path %></li>
        <li><%= link_to 'Feedback', feedback_path %></li>
      <% elsif request.path_info == '/feedback' %>
        <li><%= link_to 'Lernen und Feedback', learn_path %></li>
        <li class="active"><%= link_to 'Feedback', feedback_path %></li>
      <% else %>
        <li><%= link_to 'Lernen und Feedback', learn_path %></li>
        <% if current_user.is_admin? %> 
          <li><%= link_to 'Feedback', feedback_path %></li>
        <% end %>
      <% end %>

      <% if current_user.is_admin? %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Testgruppen für Studie
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <%= render '/shared/test_group_items' %>
          </ul>
        </li>
        <li>
          <a>Testgruppe: <%= current_user.test_group %></a>
      </li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">

      <li>
        <a><%= current_user.email %></a>
      </li>
      <li>
        <%= link_to destroy_user_session_path, method: :delete do %>
          <span class="glyphicon glyphicon-log-out"></span> Ausloggen </span>
        <% end %>
      </li>
    </ul>
  <% end %>
  </div>
</nav>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="notice"><%= notice %></div>
<% end %>
<% if alert %>
  <div class="alert alert-warning"><%= alert %></div>
<% end %>

app/views/shared/_test_group_items.html.erb
<li><%= link_to 'Testgruppe 1 - Visuelles Feedback', test_group_page_path('visual_feedback') %></li>
<li><%= link_to 'Testgruppe 2 - Textuelles Feedback', test_group_page_path('textual_feedback') %></li>
<li><%= link_to 'Testgruppe 3 - Hybrides Feedback', test_group_page_path('hybrid_feedback') %></li>
<li><%= link_to 'Testgruppe 4 - Kein Feedback', test_group_page_path('no_feedback') %></li>

app/views/shared/_test_group_panel.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Testgruppen für die Studie
  </div>
  <div class="panel-body">
    <ul>
      <%= render '/shared/test_group_items' %>
    </ul>
  </div>
</div>