config/routes.rb
Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  devise_for :users
  
  root 'learn#index'

  get 'feedback', to: 'feedback#index', as: :feedback
  get 'learn', to: 'learn#index', as: :learn
  get 'practice', to: 'skills#practice', as: :practice

  get '/test_group_page/:group' => 'test_group_pages#show', as: :test_group_page
  get '/test_group_pages' => 'test_group_pages#index', as: :test_group_pages

  resources :exercises, only: [:index, :show] do
    member do
      post 'evaluate'
    end
  end

  resources :units, only: [:index, :show]
  resources :resources, only: [:show]
  resources :learner, only: [:update]
  resources :learner_logs, only: [:destroy]
  resources :user_activity_states, only: [:create]
  resources :user_activity_logs, only: [:create]


  # applications
  resources :participant_applications do
    member do
      get 'confirmation', as: :confirmation
    end
  end

  get 'application', to: 'participant_applications#new'

  # user
  resources :users

end

app/controllers/test_group_pages_controller.rb
class TestGroupPagesController < ApplicationController
  before_filter :authenticate_user!

  before_action :fetch_learner, only: [:show]
  before_action :fetch_exercises, only: [:show]
  before_action :fetch_skills, only: [:show]

  def index

  end

  def show
    if valid_page?
        render template: "test_group_pages/#{params[:group]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  private
  
  def fetch_learner
    @learner = Learner::Learner.where(user_id: current_user.id).includes(:skill).includes(:exercises, from: :skill).index_by(&:id)
  end

  def fetch_exercises
    @exercises = Exercise.all.includes(:resources)
  end

  def fetch_skills
    @skills = Skill.includes(:children).includes(:learners).includes(:exercises).includes(:resources, from: :exercises).all.index_by(&:id)
  end
  
  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/test_group_pages/#{params[:group]}.html.erb"))
  end

end

app/views/test_group_pages/_course.html.erb
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4>Kurs</h4>
      </div>
      <div class="panel-body">   
        <% UnitCategory.where(type: UnitCategory::COURSE_TYPE).map(&:units).flatten.each do |unit| %>     
          <%= render "units/unit", unit: unit %>
        <% end %>
      </div>
    </div>  

app/views/test_group_pages/_page_header.html.erb
<div class="page-header ">
  <h1>Lerneinheiten</h1>
</div>

app/views/test_group_pages/_resources.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <b>Lern-Resourcen</b>
  </div>
  <div class="panel-body">        
    <% UnitCategory.where(type: UnitCategory::EXERCISE_TYPE).all.each do |category| %>
    <h4><%= category.name %></h4>
      <div class="list-group">
        <% category.units.each do |unit| %>
          <% unit.resources.each do |resource| %>
            <%= link_to resource.name, resource_path(resource), class: "list-group-item list-group-item-action" %>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>    

app/views/test_group_pages/hybrid_feedback.html.erb
<%= render 'page_header' %>  

<div class="col-sm-12 col-md-4 col-lg-4">
  <%= render 'course' %>
</div> 

<div class="col-sm-12 col-md-8 col-lg-8">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4>Feedback</h4>
    </div>
    <div class="panel-body">   
      <%= render 'shared/text/text', feedback: 'hybrid_feedback' %>
        <div class="hybrid-nav">
          <ul class="nav nav-tabs">
            <li class="<%= "active" if cookies[:feedback_type] == "text" %>">
              <a data-toggle="pill" href="#textual_feedback" id="text_feedback_button" class="feedback_nav">
                <b>Text-Feedback</b>
              </a>
            </li>
            <li class="<%= "active" if cookies[:feedback_type] == "visual" %>">
              <a data-toggle="pill" href="#visual_feedback" id="visual_feedback_button" class="feedback_nav">
                <b>Visuelles Feedback</b>
              </a>
            </li>
          </ul>
        </div>
        
        <div class="tab-content">
          <div id="textual_feedback" class="tab-pane fade <%= "in active" if cookies[:feedback_type] == "text" %>">
            <div class="well">
              <%= render "/feedback/text/text" %>  
            </div>
          </div>
          <div id="visual_feedback" class="tab-pane fade <%= "in active" if cookies[:feedback_type] == "visual" %>">
            <div class="well">
              <%= render "/feedback/skill_tree/skill_tree" %>
            </div>
          </div>
          <div id="default_feedback" class="tab-pane fade <%= "in active" unless cookies[:feedback_type] %>">
            <div class="well">
              Hier kannst du dein Feedback anzeigen lassen. 
              Klicke auf einen der Beiden Schalter, um dir das jeweilige Feedback anzeigen zu lassen.
            </div>
          </div>
        </div>

    </div>
  </div>      
</div> 

<%= javascript_tag do %>
  $( ".feedback_nav" ).click(function() {
    switch($(this).attr("id")) {
      case "visual_feedback_button":
        document.cookie="feedback_type= visual";
        log_it('<%= UserActivityLog::HYBRID_FEEDBACK_CHANGE_TAB %>', "visual_feedback");
        break;
      case "text_feedback_button":
        document.cookie="feedback_type= text";
        log_it('<%= UserActivityLog::HYBRID_FEEDBACK_CHANGE_TAB %>', "textual_feedback");
        break;
    }
  });

  function log_it(type, detail) {
    $.ajax({
      type: "POST",
      url: '<%= user_activity_logs_path %>',
      data: { 
        user_activity_log: { 
          event_type : type,
          detail : detail,
          user_id : '<%= current_user.id %>'
        } 
      },
      dataType: 'json'
    });
  }
<% end %>

app/views/test_group_pages/index.html.erb
<%= render '/shared/test_group_panel' %>

app/views/test_group_pages/links.html.erb
<%= link_to 'Abschluss-Fragebogen',  'https://goo.gl/forms/zf7oZNnPVArhBJ8t1' %>

app/views/test_group_pages/no_feedback.html.erb
<%= render 'page_header' %>  

<div class="row">
  <div class="col-sm-6 col-md-6 col-lg-6">
    <%= render 'course' %>
  </div> 
  <div class="col-sm-6 col-md-6 col-lg-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4>Übungen</h4>
      </div>
      <div class="panel-body"> 
        <%= render 'shared/text/text', feedback: 'no_feedback' %>
  
        <%= render '/feedback/no_feedback_tree/no_feedback_tree' %>
      </div>
    </div>     
  </div> 
  
</div> 

app/views/test_group_pages/textual_feedback.html.erb
<%= render 'page_header' %>  

<div class="row">
  <div class="col-sm-6 col-md-6 col-lg-6">
    <%= render 'course' %>
  </div> 
  <div class="col-sm-12 col-md-6 col-lg-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4>Feedback</h4>
      </div>
      <div class="panel-body">   
        <%= render 'shared/text/text', feedback: 'textual_feedback' %>

        <div class="well">
          <%= render "/feedback/text/text" %>     
        </div>
      </div>
    </div>      
  </div> 
</div> 

app/views/test_group_pages/visual_feedback.html.erb
<%= render 'page_header' %>  

  <div class="col-sm-12 col-md-4 col-lg-4">
    <%= render 'course' %>
  </div> 
  <div class="col-sm-12 col-md-8 col-lg-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h4>Feedback</h4>
      </div>
      <div class="panel-body"> 
        <%= render 'shared/text/text', feedback: 'visual_feedback' %>
  
        <%= render "/feedback/skill_tree/skill_tree" %>     
      </div>
    </div>      
  </div> 