config/routes.rb
Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  devise_for :users
  
  root 'learn#index'

  get 'feedback', to: 'feedback#index', as: :feedback
  get 'learn', to: 'learn#index', as: :learn
  get 'practice', to: 'skills#practice', as: :practice

  get '/test_group_page/:group' => 'test_group_pages#show', as: :test_group_page
  get '/test_group_pages' => 'test_group_pages#index', as: :test_group_pages

  resources :exercises, only: [:index, :show] do
    member do
      post 'evaluate'
    end
  end

  resources :units, only: [:index, :show]
  resources :resources, only: [:show]
  resources :learner, only: [:update]
  resources :learner_logs, only: [:destroy]
  resources :user_activity_states, only: [:create]
  resources :user_activity_logs, only: [:create]


  # applications
  resources :participant_applications do
    member do
      get 'confirmation', as: :confirmation
    end
  end

  get 'application', to: 'participant_applications#new'

  # user
  resources :users

end

app/views/resources/_debug_info.html.erb
<p>WP-ID: <%= "#{@resource.wp_id}"%> </p>
<p>Kompetenzen: </br> <%= @resource.skills_to_sentence %></p>
<p>Exercises: </br> <%= raw "#{@resource.sorted_exercises.map{|e| "#{e.wp_id} - #{e.id}"}.join('</br>')}"%></p>

app/views/resources/show.html.erb
<%= render '/shared/notice.html.erb' %>
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-8">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2><%= raw @resource.name %></h2>
        <p><%= raw @resource.unit.name %></p>
        <%= render 'debug_info' if ENV['DEBUG'] %>
      </div>
      <div class="panel-body">   
        <% @resource.content.split('%s').each_with_index do |content, i| %>
            <%= raw content %>
            <div class="exercise-wrapper">
              <%= render "/shared/exercise", exercise: @resource.sorted_exercises[i] if @resource.sorted_exercises[i]%>
            </div>
        <% end %>
      </div>
      <div class="panel-footer">
        <%= link_to 'Übersicht', learn_path, class: "btn btn-primary" %>
        <% if @resource.prior_resource  %>
          <%= link_to '⟽ Zurück'.html_safe, resource_path(@resource.prior_resource), class: "btn btn-bg btn-primary" if @resource.prior_resource %>
        <% else %>
          <%= link_to "⟽ Zurück", :back, class: "btn btn-primary" %>
        <% end %>
        <% if @resource.next_resource && !@resource.is_last_of_unit? %>
          <%= link_to "⟾ Weiter", resource_path(@resource.next_resource), class: "btn btn-primary pull-right next-button" %>
        <% else %>
          <%= link_to "⟾ Weiter", learn_path, class: "btn btn-primary pull-right next-button"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= javascript_tag do %>
  var logged = false;
  $(window).scroll(function() {
    if($(window).scrollTop() + $(window).height() == $(document).height()) {
      set_log();
    }
  });

  $(".next-button").click(function() { 
    set_log();
  });

  function set_log() {
    if(logged == false) {
      $.ajax({
        type: "POST",
        url: '<%= user_activity_states_path %>',
        data: { 
          user_activity_state: { 
            resource_id : '<%= @resource.id %>',
            user_id : '<%= current_user.id %>'
          } 
        },
        dataType: 'json'
      });
      logged = false;
    }
  }
<% end %>