config/routes.rb
Rails.application.routes.draw do
  mount Peek::Railtie => '/peek'

  devise_for :users
  
  root 'learn#index'

  get 'feedback', to: 'feedback#index', as: :feedback
  get 'learn', to: 'learn#index', as: :learn
  get 'practice', to: 'skills#practice', as: :practice

  get '/test_group_page/:group' => 'test_group_pages#show', as: :test_group_page
  get '/test_group_pages' => 'test_group_pages#index', as: :test_group_pages

  resources :exercises, only: [:index, :show] do
    member do
      post 'evaluate'
    end
  end

  resources :units, only: [:index, :show]
  resources :resources, only: [:show]
  resources :learner, only: [:update]
  resources :learner_logs, only: [:destroy]
  resources :user_activity_states, only: [:create]
  resources :user_activity_logs, only: [:create]


  # applications
  resources :participant_applications do
    member do
      get 'confirmation', as: :confirmation
    end
  end

  get 'application', to: 'participant_applications#new'

  # user
  resources :users

end

app/models/unit.rb
class Unit
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String

  belongs_to :category, class_name: "UnitCategory"  
  has_many :resources

  def skills
    resources.map {|r| r.exercises.map {|e| e.skills }}.flatten.uniq
  end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :authenticate_user!
  before_action :fetch_categories, only: [:index]
  before_action :fetch_unit, only: [:show]

  def fetch_categories
    @categories = UnitCategory.all
    
  end

  def fetch_unit
    @unit = Unit.find params[:id]
  end
end

app/views/units/_category.html.erb
    
<div class="panel panel-primary">
  <div class="panel-heading">
    <b><%= category.name %></b>
  </div>
  <div class="panel-body">        
    <% category.units.each do |unit| %>
      <%= render 'unit', unit: unit%>
    <% end %>
  </div>
</div>      

app/views/units/_unit.html.erb
<div class="panel">
  <div class="panel-heading">
    <h4><%= unit.name %></h4>
  </div>
  <div class="panel-body">
    <div class="list-group">
      <% unit.resources.each do |resource| %>
        <% if UserActivityState.find_or_create_by(user: current_user).current_resource == resource %>
          <%= link_to resource_path(id: resource.id), class: "list-group-item list-group-item-action list-group-item-warning" do %>
            <span><b><%=  "#{resource.name}" %></b></span>
          <% end %>
        <% elsif UserActivityState.find_or_create_by(user: current_user).resource_ids.include?(resource.id) %>
          <%= link_to resource_path(id: resource.id), class: "list-group-item list-group-item-action list-group-item-success" do %>
            <span><%=  "#{resource.name}" %></span>
            <span class="badge badge-secondary">abgeschlossen</span>
          <% end %>
        <% else %>
          <%= link_to "#{resource.name}", resource_path(id: resource.id), class: "list-group-item list-group-item-action" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/units/index.html.erb
<%= render '/shared/notice.html.erb' %>

<div class="page-header clearfix">
  <h1>Lerneinheiten</h1>
</div>

<div class="row">
    <% @categories.courses.each do |category| %>
      <div class="col-sm-12 col-md-6 col-lg-4">
          <%= render 'category', category: category%>
      </div>
  <% end %>
  <% @categories.exercises.each do |category| %>
    <div class="col-sm-12 col-md-6 col-lg-4">
      <%= render 'category', category: category%>
    </div>
  <% end %>
</div>

app/views/units/show.html.erb
<%= render '/shared/notice' %>

<div class="page-header clearfix">
  <h1>Lerneinheit</h1>
</div>
<div>
  <%= render 'unit', unit: @unit %>
</div>
<div>
  <br />
  <%= link_to 'Zurück', units_path, class: "btn" %>
</div>